Feat/Radial angle distance as a neighbor list filter
glotzerlab/freud pull request #1075
Opened 2023-02-20 19:06 UTC by DomFijan

## Description
This PR implements [RAD](https://aip.scitation.org/doi/10.1063/1.4961439) (radial angle distance) method as a neighbor list filter. 

## Motivation and Context
A good parameter free neighbor list method.

## How Has This Been Tested?
Tests were added, we might need more.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [ ] All new and existing tests passed.
- [ ] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

2023-04-05 20:38 UTC, SchoeniPhlippsn requested changes
Overall it looks good. I only have a few comments that should be addressed.

2023-04-05 20:38 UTC, SchoeniPhlippsn commented on cpp/locality/Filter.h
> +    //<! algorithm implementation cannot guarantee all neighbors have filled shells
```suggestion
    //<! algorithm implementation cannot guarantee that all neighbors have completely filled shells
```

2023-04-05 20:38 UTC, SchoeniPhlippsn commented on cpp/locality/Filter.h
> +     * with.
```suggestion
     * In general, the filter concept cannot guarantee that each query point will have
     * a completely filled shell according to the implemented algorithm. This happens 
     * when the initial unfiltered neighbor list doesn't have enough neighbors to
     * guarantee this criterion.
```

2023-04-05 20:38 UTC, SchoeniPhlippsn commented on cpp/locality/FilterRAD.cc
> +                    if (1 / dot(v1, v1) < (coz / dot(v2, v2)))
To prevent divisions and as all numbers in the denominator are positive I would just write this as 
```suggestion
                    if ( (dot(v2, v2) * sorted_dist(first_idx + j) * sorted_dist(first_idx + k)) < (dot(v1,v2) * dot(v1, v1 )) )
```

2023-04-05 20:38 UTC, SchoeniPhlippsn commented on cpp/locality/FilterRAD.cc
> +                    // if a particle blocks j and we are doing RAD closed
```suggestion
                    // if a particle blocks j and "RAD-closed" is requested
```

2023-04-05 20:38 UTC, SchoeniPhlippsn commented on doc/source/reference/freud.bib
> +author = {Higham,Jonathan  and Henchman,Richard H. },
```suggestion
author = {Higham,Jonathan and Henchman,Richard H. },
```

2023-04-05 20:38 UTC, SchoeniPhlippsn commented on freud/locality.pyx
> +    further away than a blocked particle.
This only applies in the terminate-after-blocked-mode!

2023-04-05 20:38 UTC, SchoeniPhlippsn commented on freud/locality.pyx
> +    of the neighborlist filter concept in **freud**, see :class:`.Filter`.
```suggestion
    RAD is implemented as a filter for pre-existing sets of neighbors due to 
    the high performance cost of sorting all :math:`N^2` particle pairs by 
    distance. For a more in-depth explanation of the neighborlist filter 
    concept in **freud**, see :class:`.Filter`.
```

2023-04-05 20:38 UTC, SchoeniPhlippsn commented on tests/test_locality_Filter.py
> +        which derived classes should use as a starting point for their implementations.
I don't understand this sentence

2023-04-14 15:25 UTC, SchoeniPhlippsn approved these changes
Despite the misspelling of my name it looks good to me

2023-04-14 15:25 UTC, SchoeniPhlippsn commented on doc/source/reference/credits.rst
> +Philip Schonhofer
```suggestion
Philipp Schönhöfer
```

2023-04-14 18:04 UTC, DomFijan commented
Tests now fail due to codecov. We can wait until this gets fixed on master (#1097)?

2023-04-21 19:43 UTC, merged