Fix License Headers
glotzerlab/freud pull request #1085
Opened 2023-03-20 17:50 UTC by tommy-waltmann

## Description

This PR adds a pre-commit hooks which updates the license headers on every file in freud to be consistent with the header in the `LICENSE` file. This PR also updates the year in freud's license file to be 2023

## Motivation and Context

The year on the license headers in freud is still 2020. This PR will create an easy to maintain solution to the problem of updating the headers every year.

Resolves: #1084 

## How Has This Been Tested?

I have run `pre-commit` and it seems that all necessary files have had their headers updated correctly.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [ ] All new and existing tests passed.
- [ ] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

2023-03-20 18:26 UTC, joaander requested changes
I'm glad you found my `fix-license-headers` script useful.

One change: The rendered sphinx docs should show 2023 as well, but do not:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/2197568/226432138-8daf193a-2a0d-40c8-bea1-9bdc9db09ee8.png">

In HOOMD and other packages, I use this in `conf.py` to set the copyright to the current date at the build time:
```
import datetime
...
year = datetime.date.today().year
copyright = f'2009-{ year } The Regents of the University of Michigan'
```

2023-03-20 20:41 UTC, tommy-waltmann commented
The `pre-commit` failure here is an interesting corner case. The script returns 1 (indicating failure for pre-commit) on a file in which the header is the only text in the file, even though no updates are made to the header.

Some options are manually excluding the offending file or completing a PR to the `fix-license-header` tool to return 0 in these cases. Any thoughts about which option is preferred @joaander ?

2023-03-21 12:18 UTC, joaander commented
Thanks for finding the bug in `fix-license-headers`. I just pushed a fix.

2023-03-21 12:46 UTC, joaander approved these changes
Thanks!

2023-03-21 16:46 UTC, merged