Drop python 3.7
glotzerlab/freud pull request #1167
Opened 2023-10-25 19:02 UTC by tommy-waltmann

## Description

This PR removes support for python 3.7 by dropping it from our testing matrix and build wheels operations.

## Motivation and Context

Python 3.7 hit end of life in June: https://devguide.python.org/versions/

## How Has This Been Tested?

If the current tests pass, we are ready to do.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [ ] All new and existing tests passed.
- [ ] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

2023-10-26 19:33 UTC, b-butler requested changes
Some comments need to be updated.

2023-10-26 19:33 UTC, b-butler commented on .github/workflows/cibuildwheel-before-test.sh
>    # Python 3.7 is only supported with oldest requirements
```suggestion
  # Python 3.8 is only supported with oldest requirements
```

2023-10-26 19:33 UTC, b-butler commented on .github/workflows/cibuildwheel-before-test.sh
>    # Python 3.8 needs compatible requirements
```suggestion
  # Python 3.9 needs compatible requirements
```

2023-11-02 15:33 UTC, tommy-waltmann commented
@b-butler would appreciate a review here, this PR is holding up all the new dependabot PRs.

2023-11-06 13:26 UTC, merged