Port environment to nanobind
glotzerlab/freud pull request #1291
Opened 2024-11-01 22:24 UTC by DomFijan

## Description
Part of nanobind porting efforts.

## How Has This Been Tested?
Previous testing infrastructure is being reused.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [ ] I have updated the [credits](https://github.com/glotzerlab/freud/blob/main/doc/source/reference/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/main/ChangeLog.md).

2025-02-03 17:16 UTC, joaander requested changes
Thanks! There are a few TODO items that need to be addressed or removed.

2025-02-03 17:16 UTC, joaander commented on freud/locality.py
> +    @property  # TODO: Actual shape is 2, (d1=1, d2+1) and type is list
Address the TODO items in this file or remove them.

2025-02-03 17:16 UTC, joaander commented on freud/util/ManagedArray.h
> +        return m_data.data(); // TODO: not valid for std::vector<bool>
I think we handled this in a different way, correct?
```suggestion
        return m_data.data();
```

2025-02-03 17:16 UTC, joaander commented on freud/util/export-ManagedArray.h
> +#include <complex>
Try moving this to `freud/util/export-ManagedArray.cc`. If that doesn't work, we will need to ignore the clang-tidy lint on this line.

2025-02-03 19:10 UTC, janbridley commented on freud/locality.py
> +    @property  # TODO: Actual shape is 2, (d1=1, d2+1) and type is list
Fixed in [dfd0b04](https://github.com/glotzerlab/freud/pull/1291/commits/dfd0b04024b7b9cbc48a26a9d5e78d8d16db167c)

2025-02-04 15:19 UTC, joaander approved these changes
Thanks!

2025-02-04 15:19 UTC, merged