Fix/pypi deployment
glotzerlab/freud pull request #229
Opened 2019-02-21 02:08 UTC by vyasr

This fixes some of the PyPI deployment issues we experienced with 1.0. The Linux issue is fixed by manually checking out the code instead of using CircleCI's checkout script, which forces cloning over ssh on this VM that's too old to handle it. The Mac deployment had a bug that was causing it to just retest the same Python version's installation of freud multiple times, which I've fixed, but the underlying cause of the deployment failure is still present. The problem there appears to be in the most recent release of SciPy. I've opened issue scipy/scipy/#9858, we can see if they're able to solve that problem.

2019-02-21 02:44 UTC, bdice commented
@vyasr Can you fix whatever appears to be the diff in the `fsph` submodule? I think you might have committed that by accident but it's behind `master`.

2019-02-21 02:45 UTC, bdice requested changes

2019-02-21 02:45 UTC, bdice commented on .circleci/config.yml
> +        export CIRCLE_TAG=v1.0.0  # Hard code for testing
@vyasr You need to remove this, right?

2019-03-05 21:52 UTC, vyasr commented
@bdice fixed

2019-03-05 21:56 UTC, bdice approved these changes

2019-03-05 22:09 UTC, merged