Feature/neigbor list getitem
glotzerlab/freud pull request #238
Opened 2019-03-15 18:47 UTC by k-l-wang

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-03-15 21:00 UTC, bdice requested changes
Thanks for the pull request! 😄 This is a nice feature and I am excited to use this in my code. Please see the change requests that I have written and let me know if you have any questions!

2019-03-15 21:00 UTC, bdice commented on doc/source/credits.rst
> +    of this software and associated documentation files (the "Software"), to dealhbor
@k-l-wang Can you fix this? 😆

2019-03-15 21:00 UTC, bdice commented on tests/test_locality_NeighborList.py
> +        assert len([x for x in self.cl.nlist]) == len(self.cl.nlist.index_j)
I think this is equivalent to saying `assert len(self.cl.nlist) == len(self.cl.nlist.index_j)`. Can you make that change to simplify the test?

2019-03-23 17:09 UTC, vyasr commented on doc/source/credits.rst
> +    of this software and associated documentation files (the "Software"), to dealhbor
I fixed this typo!

2019-03-23 17:28 UTC, vyasr commented
@bdice I fixed the minor typos. Feel free to merge once you go through another round of review (I'll leave it to you since you requested changes).

2019-04-17 17:50 UTC, bdice approved these changes

2019-04-17 17:50 UTC, merged