Rewrite neighbor finding in freud
glotzerlab/freud pull request #241
Opened 2019-03-16 02:25 UTC by vyasr

## Description
This pull request defines a new API for lazily finding and iterating over neighbors by separating the building of the acceleration structure from the querying of neighbors. This API supports efficiently querying the same data structure an arbitrary number of times for new neighbors. Additionally, neighbors can be retrieved as lists or using a lazy generator.

## Motivation and Context
This change makes it possible to reuse data structures that accelerate neighbor queries for a given set of data. Reusing these data structures will allow sequences of analyses on the same data to proceed much more efficiently. The ability to iteratively extract neighbors of a point without building a NeighborList will also provide performance gains since it avoids the overhead of looping twice to build the structure and then query it.

## How Has This Been Tested?
Extensive unit tests have been added in the `test_locality_NeighborQuery.py` module. These tests mirror the existing tests for the LinkCell class but are modified to use the new API for the LinkCell class (and for the AABBQuery class, which does not support the old `compute`-based API).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-04-17 19:09 UTC, bdice requested changes
I have a few minor comments/suggestions to resolve. Overall, this is great work, @vyasr. Thanks so much!

2019-04-17 19:09 UTC, bdice commented on cpp/locality/LinkCell.cc
> +        // will only check if the box is not null
The order of these comments is confusing. Perhaps write `// Check if the box is not null` here, and `// Check if the box is too small` above the `if` statement below.

2019-04-17 19:09 UTC, bdice commented on freud/_locality.pxd
> +        bool operator==(NeighborPoint)
Should this interface also expose the distance-based comparator?

2019-04-17 19:09 UTC, bdice commented on freud/locality.pyx
> +        if self.query_type == 'nn':
Would it be possible to refactor this so that `self.iterator` is returned by a function or property that does all this? It would reduce duplication between `__iter__` and `toNList` as well as duplication with `AABBQueryResult` since that would be able to just define its corresponding function differently and use the parent class's methods for everything else.

2019-04-17 19:09 UTC, bdice commented on freud/locality.pyx
> +        return self.box
How does this know to return the C++ box...? Is this duplicated name too confusing?

2019-04-17 19:09 UTC, bdice commented on freud/locality.pyx
> +            The points associated with this class, if used in the new mode
"in the new mode" -> "as a NeighborQuery object"?

2019-04-19 05:05 UTC, vyasr commented on freud/locality.pyx
> +        if self.query_type == 'nn':
Good call, that cleans this up quite a bit.

2019-04-19 05:12 UTC, vyasr commented on freud/locality.pyx
> +        return self.box
Yeah, that's a good call. Note that we don't want to return the C++ box, we want to return a Python object, but I agree that the conflict between the property name and the member is bad. I'll modify this.

2019-04-19 05:16 UTC, vyasr commented on freud/locality.pyx
> +            The points associated with this class, if used in the new mode
Yup, I'll clarify.

2019-04-23 18:29 UTC, bdice approved these changes
👍 great work, you rock!

2019-04-23 19:43 UTC, merged