Refactoring convert array
glotzerlab/freud pull request #307
Opened 2019-06-11 18:11 UTC by jinsoo960

## Description

Shape check moved into `convert_array` function.
`squeeze` and `atleast_2d` is not implemented yet.

## Motivation and Context

#199 #268 

## How Has This Been Tested?

Few tests have been added and it passes all the existing tests.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

2019-06-12 20:55 UTC, vyasr requested changes
After discussion, we'd like to merge the shape and dimension checks into one check. That should simplify this further.

2019-06-13 03:01 UTC, jinsoo960 commented
Done! 
One side note:
I was in the branch `feature/property` and there `common` is a `pyx` file and thus produces a `common.cpython-36m-darwin.so` file in the directory `freud`.
When I checked out this branch, that `common.cpython-36m-darwin.so` file still exists, and importing `common` will not import `common.py`, but instead will import the implementation in `common.cpython-36m-darwin.so` file. (This can be checked from just opening a python interpreter and try printing `freud.common.__file__`.)
It really messed things up on my local machine because all the changes to `common.py` does not get reflected, and even running `python setup.py clean` does not clean it.

2019-06-13 13:42 UTC, vyasr commented
Thanks for the heads up. Makes sense, that annoyance probably won't go away until we merge that branch, so good to keep it in mind.

2019-06-13 14:09 UTC, vyasr approved these changes
Everything looks good! There were a couple of small things I wanted changed, but they were were all tiny changes so it made more sense for me to just make them myself.

2019-06-13 14:09 UTC, vyasr commented on freud/box.pyx
> +        imgs = freud.common.convert_array(imgs, (None, ) * vecs.ndim,
Can you just make this check `vecs.shape` and then remove the extra check above?

2019-06-13 14:59 UTC, bdice commented on freud/cluster.pyx
>              keys((:math:`N_{particles}`) :class:`numpy.ndarray`):
Is this missing a space after `keys`?

2019-06-13 15:00 UTC, bdice commented on freud/cluster.pyx
> +            cluster_idx, dtype=np.uint32, shape=(points.shape[0],))
Switch the order of arguments.

2019-06-13 15:00 UTC, bdice commented on freud/common.py
>          dtype: code:`dtype` to convert the array to if :code:`array.dtype`
Missing colon before `code:` ➡️ `:code:`

2019-06-13 15:03 UTC, bdice commented on freud/environment.pyx
> +                shape=(points_ref.shape[0], 4)) # noqa
Not sure why this is `# noqa` - is there a `flake8` complaint? I like to mark `# noqa E501` or whatever the `flake8` rule is that it breaks.

2019-06-13 15:05 UTC, bdice commented on freud/locality.pyx
> +                                            (None, None))
Why not `shape=(None, 3)`?

2019-06-13 15:06 UTC, bdice commented on freud/locality.pyx
> +        index_j = freud.common.convert_array(index_j, (None,), dtype=np.uint64)
We could get rid of the shape check below by enforcing `index_j` has the same shape as `index_i`.

2019-06-13 15:07 UTC, bdice commented on freud/locality.pyx
> +            weights = freud.common.convert_array(weights, (None, ))
Check to make sure it's the same shape as `index_i`.

2019-06-13 15:08 UTC, bdice commented on freud/locality.pyx
> +                points, (None, None)).copy()
As above, can we check for shape `(None, 3)`?

2019-06-13 15:08 UTC, bdice commented on freud/locality.pyx
> +            np.atleast_2d(points), (None, None))
`(None, 3)`?

2019-06-13 15:09 UTC, bdice commented on freud/msd.pyx
> +            images = freud.common.convert_array(images, dtype=np.int32,
Swap dtype and shape.

2019-06-13 15:09 UTC, bdice commented on freud/order.pyx
> +        self.u = freud.common.convert_array(u, (None, ))
Should be shape `(3,)`

2019-06-13 15:13 UTC, bdice commented
We're pretty inconsistent throughout about whether we define the shape as a keyword argument or just a plain argument, like `freud.common.convert_array(arr, shape=(None, 3))` vs. `freud.common.convert_array(arr, (None, 3))`. I like defining it as a keyword argument for clarity, but that's a stylistic preference. Consistency would be good either way.

2019-06-13 15:15 UTC, bdice commented
Also check for other instances of the `(None, None)` pattern that I mentioned - I stopped leaving comments after the first few. It doesn't seem right to me (should be `(None, 3)` if I understand correctly) but it was repeated a lot so I may have misinterpreted something.

2019-06-13 15:15 UTC, bdice requested changes
See comments.

2019-06-13 15:51 UTC, vyasr commented
The majority of cases were using keyword args, so I switched to doing that everywhere.

2019-06-13 23:15 UTC, bdice approved these changes
One doc fix - then good to merge. 👍

2019-06-13 23:15 UTC, bdice commented on freud/environment.pyx
> +            ref_points ((:math:`N_{ref_points}`, 3) :class:`numpy.ndarray`):
I think the docs will render this wrong unless you escape the underscore. Please check.

2019-06-14 15:51 UTC, merged