Change clustering algorithm to use connected components
glotzerlab/freud pull request #408
Opened 2019-08-25 04:04 UTC by bdice

## Description
In previous versions of freud, the cluster algorithm has looped over bonds in the NeighborList/NeighborQuery and used a cutoff radius to filter those bonds. That is, two particles are in the same cluster if and only if there is a path between them in the network of bonds, where every bond distance along that walk is less than `r_cut`. This is annoying for two reasons:

1. If this behavior is desired, it's easy to just filter the network of bonds beforehand.
2. It is not straightforward to use a network of bonds formed by some criterion other than distance (unless you fake it by producing a NeighborList and using an arbitrarily high value of `r_cut`).

## Motivation and Context
By rewriting this, it becomes much easier to use this module for the clustering performed by the Solid-Liquid order parameter.

## How Has This Been Tested?
Existing tests pass.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [ ] All new and existing tests passed.
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

2019-08-25 04:06 UTC, bdice commented
## To-do:
- [ ] Update documentation
- [ ] Improve description of behavior with `keys`
- ...

2019-08-27 17:23 UTC, vyasr requested changes

2019-08-27 17:23 UTC, vyasr commented on cpp/cluster/Cluster.cc
> +        label_min_id[label_map[s]] = std::min(label_min_id[label_map[s]], i);
Since you're iterating over the particles in order, won't the smallest index always be the first one you find? So in the conditional you can just set `label_min_id[cur_set] = i` and be done?

2019-08-27 17:23 UTC, vyasr commented on cpp/cluster/Cluster.cc
>      m_num_clusters = cur_set;
Get rid of `cur_set` and just use `m_num_clusters`.

2019-08-27 17:23 UTC, vyasr commented on cpp/cluster/Cluster.cc
> +    map<size_t, size_t> label_min_id;
Make `label_min_id` a vector to start with, then you don't copy it into a vector again later. Requires that you allocate it to be the size of the number of particles to start with (and probably resize to m_num_clusters later), but in general freud assumes we're compute and not memory bound anyway. You can call `shrink_to_fit` afterwards if you're concerned about memory usage.

2019-08-27 17:23 UTC, vyasr commented on cpp/cluster/Cluster.cc
> +    map<size_t, size_t> label_min_id;
I think you can do the same thing with `label_counts` as well.

2019-08-27 17:23 UTC, vyasr commented on cpp/cluster/Cluster.cc
> +        v.clear();
Honestly this might be simpler if you just recreate the cluster keys every time (or at least if the number of clusters changes).

2019-08-27 17:23 UTC, vyasr commented on freud/cluster.pyx
> +            l_keys_ptr = &l_keys[0]
I propose treating `keys=None` as "don't bother to compute keys". We could add some special key like " 'clusters' " or "{auto}" that indicates the behavior you've implemented. That would allow us to avoid doing the extra work for building the keys if the user won't ever use them.

2019-08-27 17:23 UTC, vyasr commented on freud/cluster.pyx
> +            l_keys_ptr = &l_keys[0]
What's currently being done in C++ in the default case could be accomplished by just creating an array in Python with `np.arange(points.shape[0])` and passing that through.

2019-08-28 00:46 UTC, bdice commented on freud/cluster.pyx
> +            l_keys_ptr = &l_keys[0]
Discussed further in person - assuming keys are the particle IDs seems like a useful default behavior, based on what current users get from this class.

2019-09-09 19:08 UTC, vyasr requested changes

2019-09-09 19:08 UTC, vyasr commented on cpp/cluster/Cluster.cc
> +                      const vec3<float>* points, unsigned int Np,
No need to pass in these extra points arguments, just pull out of the `nq` object.

2019-09-09 19:08 UTC, vyasr commented on cpp/cluster/Cluster.cc
> +    vector<size_t> cluster_min_id(m_num_particles);
For consistency with `cluster_label`, do you also want to initialize this to `-1`? It should never be necessary, but would let you sanity check things if needed (since 0 is a valid id).

2019-09-09 19:08 UTC, vyasr commented on cpp/cluster/Cluster.cc
> +    cluster_min_id.resize(m_num_clusters);
Doesn't really matter, but as I mentioned when I first requested this rewrite you could call [shrink_to_fit](https://en.cppreference.com/w/cpp/container/vector/shrink_to_fit) if you're still concerned about memory overhead. Up to you.

2019-09-09 19:08 UTC, vyasr commented on cpp/cluster/Cluster.h
> -*/
Please put the docstring back, updated as needed.

2019-09-09 19:08 UTC, vyasr commented on cpp/cluster/Cluster.h
> +                 const vec3<float>* points, unsigned int Np,
Update signature, same as in cc file.

2019-09-09 19:08 UTC, vyasr commented on cpp/cluster/Cluster.h
> +    //! Get a reference to the last computed cluster ids
Add a period.

2019-09-09 19:08 UTC, vyasr commented on cpp/cluster/Cluster.h
> +    //! Returns the last computed cluster keys
Add a period.

2019-09-09 19:08 UTC, vyasr commented on freud/_cluster.pxd
>                       unsigned int,
Update signature.

2019-09-09 19:42 UTC, vyasr approved these changes

2019-09-09 19:42 UTC, merged