Refactor more variable names.
glotzerlab/freud pull request #418
Opened 2019-08-28 16:22 UTC by bdice

## Description
This PR is a continuation of #355, with mostly changes that I requested and some that I didn't. I forgot to "submit" my PR review so these didn't make it into that PR. Lots of documentation fixes here.

## Motivation and Context
Consistency is the ~hobgoblin~ saving grace of copy-pasting minds.

## How Has This Been Tested?
Existing tests have been updated to use more consistent names.

## Types of changes

- [x] Mostly docs and minor refactoring 📝

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

2019-08-28 16:24 UTC, bdice commented
@vyasr This will be terrible to review -- I was as meticulous as I could be while making the changes, and we have agreed on virtually all of these name changes previously, in #355 or in person. Feel free to just take a quick glance if you don't want to get stuck in the weeds here.

2019-09-03 16:39 UTC, vyasr requested changes
Pretty much just need to do some more `r_cut`->`r_max` renames then it's good.

2019-09-03 16:39 UTC, vyasr commented on cpp/cluster/Cluster.h
> +    float m_r_cut;                 //!< Maximum r at which points will be counted in the same cluster
Change to r_max.

2019-09-03 16:39 UTC, vyasr commented on cpp/density/GaussianDensity.h
> +    float m_r_cut;                                 //!< Max r at which to compute density
Change to `m_r_max`.

2019-09-03 16:39 UTC, vyasr commented on cpp/density/LocalDensity.h
> +    float m_r_cut;         //!< Maximum neighbor distance
Change to `r_max`.

2019-09-03 16:39 UTC, vyasr commented on cpp/locality/AABBQuery.cc
> +            throw std::runtime_error("The AABBQuery r_cut is too large for this box.");
`r_max`

2019-09-03 16:39 UTC, vyasr commented on cpp/locality/NearestNeighbors.cc
> +    const float r_cut_sq(m_lc->getCellWidth() * m_lc->getCellWidth());
`r_max_sq`

2019-09-03 16:39 UTC, vyasr commented on cpp/order/SolLiq.h
> +    void setClusteringRadius(float r_cut_cluster)
`r_max_cluster`

2019-09-03 16:39 UTC, vyasr commented on cpp/order/SolLiq.h
> +                "SolLiq requires that r_cut_cluster must be greater than r_cut (for local env).");
`r_max_cluster`, `r_max`

2019-09-03 18:22 UTC, merged