Fix/from system dimensionality
glotzerlab/freud pull request #545
Opened 2019-11-05 00:37 UTC by vyasr

## Description
I adapted `from_system` to correctly handle inputs from various data sources when the systems are 2-dimensional. I also fixed an error in how Ovito inputs were handled.

## Motivation and Context

Currently the code simply passes the underlying object from various inputs through. This method doesn't work for 2D systems unless the object actually provides a `dimensions` attribute. Additionally, the current version will be a bit noisy for HOOMD outputs that set `Lz=1` for 2D systems, so we need to construct the box explicitly to silence these. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [ ] All new and existing tests passed.
- [ ] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

2019-11-05 18:04 UTC, bdice requested changes
Changes requested.

2019-11-05 18:04 UTC, bdice commented on ChangeLog.md
> +* Conversion of automatic conversion of 2D systems from various data sources.
```suggestion
* Automatic conversion of 2D systems from various data sources.
```

2019-11-05 18:04 UTC, bdice commented on freud/locality.pyx
> +                            "from_system (or manually convert the frame's box "
Manually convert the frame's box? That doesn't make sense to me.

Also I asked Oliver Beckstein just now and MDAnalysis doesn't formally support 2D systems.

2019-11-05 18:04 UTC, bdice commented on freud/locality.pyx
> +            box = freud.Box(system.box.Lx, system.box.Ly, xy=system.box.xy)
Seems like this breaks 3D compatibility?

2019-11-05 18:04 UTC, bdice requested changes
Changes requested.

2019-11-06 20:20 UTC, vyasr commented on freud/locality.pyx
> +                            "from_system (or manually convert the frame's box "
OK, then I'll just remove this warning and we'll assume inputs are 3D.

2019-11-06 20:24 UTC, vyasr commented on freud/locality.pyx
> +            box = freud.Box(system.box.Lx, system.box.Ly, xy=system.box.xy)
Good catch, yes.

2019-11-06 20:28 UTC, bdice approved these changes
LGTM!

2019-11-06 20:39 UTC, merged