added r_min and r_max to the RDF & NeighborList classes
glotzerlab/freud pull request #825
Opened 2021-08-29 08:24 UTC by SyedZiaul

change cpp/density/RDF.cc file
change  cpp/locality/NeighborList.cc file

2021-08-29 13:44 UTC, bdice requested changes
Hi @SyedZiaul, it looks like you made a new GitHub account? Please avoid making multiple pull requests to address the same issue. You already opened #822 and #824 -- should those pull requests be closed?

Please see my code suggestions for changes.

2021-08-29 13:44 UTC, bdice commented on cpp/density/RDF.cc
> +        throw std::invalid_argument("RDF requires r_min to be non-negetive.");
```suggestion
        throw std::invalid_argument("RDF requires r_min to be non-negative.");
```

2021-08-29 13:44 UTC, bdice commented on cpp/locality/NeighborList.cc
> +    }
```suggestion
    if (r_max <= 0)
    {
        throw std::invalid_argument("NeighborList.filter_r requires r_max to be positive.");
    }
    if (r_min < 0)
    {
        throw std::invalid_argument("NeighborList.filter_r requires r_min to be non-negetive.");
    }
    if (r_max <= r_min)
    {
        throw std::invalid_argument("NeighborList.filter_r requires that r_max must be greater than r_min.");
    }
```

2021-08-29 14:33 UTC, SyedZiaul commented
@bdice okay i will keep it in mine mind, for the next time. i will not opened multiple pull request for same issue.

2021-08-29 15:09 UTC, SyedZiaul commented
@bdice i closed #824 and #822 pull request. if their is any changes to be made in this regards , you can tell me.

2021-08-29 15:57 UTC, bdice requested changes
These changes will need to be accompanied by tests in the Python code. Please see examples here:

https://github.com/glotzerlab/freud/blob/2d989e0744beed8bb4194c587492ed1e3440578e/tests/test_density_RDF.py#L66-L73

Similar tests will be needed for `NeighborList.filter_r` in this file; https://github.com/glotzerlab/freud/blob/master/tests/test_locality_NeighborList.py#L38

Please create a new test function called `test_filter_r_invalid_arguments` for your new code in that file.

2021-08-29 15:57 UTC, bdice commented on cpp/density/RDF.cc
> +        if (r_min < 0)
Please check the indentation style. I keep requesting the same changes on every review.
```suggestion
    if (r_min < 0)
```

2021-08-29 15:57 UTC, bdice commented on cpp/locality/NeighborList.cc
> +
Delete this empty newline.
```suggestion
```

2021-08-29 15:57 UTC, bdice commented on cpp/locality/NeighborList.cc
> +        if (r_min < 0)
```suggestion
    if (r_min < 0)
```

2021-08-29 16:42 UTC, SyedZiaul reviewed
@bdice any other changes need to made ?

2021-08-29 21:23 UTC, bdice commented
> 
> 
> @bdice any other changes need to made ?

Please see my previous comment about adding tests. https://github.com/glotzerlab/freud/pull/825#pullrequestreview-741128899

2021-08-30 13:36 UTC, SyedZiaul commented
@bdice i added this test function
### def test_filter_r_invalid_arguments(self):
        # Make sure that invalid NeighborList.filter_r objects raise errors
        with pytest.raises(ValueError):
            freud.locality.NeighborList.filter_r(r_max=0, r_min=1)
        with pytest.raises(ValueError):
            freud.locality.NeighborList.filter_r(r_max=1, r_min=-1)
        with pytest.raises(ValueError):
            freud.locality.NeighborList.filter_r(r_max=1, r_min=2)

i am getting some error , plz check?

2021-09-06 19:36 UTC, bdice commented
@SyedZiaul I pushed a couple changes to this PR to fix the tests. See commits 53dc730 and f5658b5. I also applied our pull request message template to the PR description. Please fill out the pull request description above (by editing the PR description message) and update the credits/changelog. You can add a section at the bottom of the credits with your name. Once the PR template is filled out and the credits and changelog are updated, this should be ready to merge.

Some additional work is needed to fully resolve #821. I would recommend making a separate PR for these changes.
- [ ] Throw errors for invalid `r_max` and `diameter` arguments in LocalDensity.cc (see comments on #824, #822)
  - [ ] r_max > 0; must be positive
  - [ ] diameter >= 0; must be non-negative
- [ ] Throw errors for invalid arguments in the constructor of `NeighborQueryPerPointIterator`: https://github.com/glotzerlab/freud/blob/7d5662e614019f2b06493bb0a86b1ad8933bf4f3/cpp/locality/NeighborQuery.h#L262-L268
- [ ] Add tests for the errors mentioned above.

2021-09-06 19:38 UTC, bdice requested changes
This PR looks mostly complete, except for the changelog / credits I mentioned in my comment above.

2021-09-29 03:07 UTC, vyasr commented
@SyedZiaul would you be able to finish up this PR? It looks like all that's left for you to do is update the PR template description above and update the changelog and credits.

2021-10-06 20:06 UTC, Charlottez112 commented
This seems good to go. I'll finish up what's left

2021-10-06 20:31 UTC, Charlottez112 commented
I'm not sure how I should update the changelog, so I'll just write it here:

## Change log

### Added
  * Added error checking for `r_min`, `r_max` in `freud.density.RDF` and `freud.locality.NeighborList`

2021-10-06 20:31 UTC, Charlottez112 approved these changes
Thank you for the work!

2021-10-06 22:38 UTC, bdice commented
@Charlottez112 I'll edit this file: https://github.com/glotzerlab/freud/blob/master/ChangeLog.md

Then we can merge!

2021-10-06 22:40 UTC, bdice approved these changes

2021-10-06 22:51 UTC, merged