Add Python 3.10 builds, disable musl.
glotzerlab/freud pull request #863
Opened 2021-11-01 23:57 UTC by bdice

## Description
Disables failing musl builds which were added in #862. Also enabled cibuildwheel for Python 3.10.

## How Has This Been Tested?
This is good to go if CI passes!

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:
- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [ ] All new and existing tests passed.
- [ ] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

2021-11-02 00:34 UTC, bdice commented on ChangeLog.md
> +
```suggestion
```

2021-11-21 20:30 UTC, bdice commented
Still seeing some issues with getting scipy wheels here. It looks like the failure to install scipy from wheels or from source also prevents other testing dependencies from being installed properly (matplotlib, garnett, gsd, sympy), resulting in failed tests.

2021-11-26 21:35 UTC, bdice commented
The new version of scipy works, so I think this is ready to review and merge.

2021-11-27 22:20 UTC, tommy-waltmann requested changes
We need to actually be running the unit tests in a python 3.10 environment, not just confirming that we can build freud against python 3.10.

2021-11-27 23:03 UTC, bdice commented
@tommy-waltmann cibuildwheel also runs all unit tests. https://github.com/glotzerlab/freud/blob/b0110550a8bba529c422051b24340c49eeb6e073/.github/workflows/build_wheels.yml#L57-L61

I would treat cibuildwheel as our "primary" CI at this point. We've only kept the other CircleCI tests for two reasons, in my recollection:
- We don't have Windows tests on cibuildwheel yet. See stalled PR #749.
- We don't run the "style check" job with cppcheck and clang-tidy on GitHub Actions (not really a job for cibuildwheel).

I believe the other CircleCI tests for Linux are redundant with those in cibuildwheel (aside from minor differences in the underlying CI images like compiler versions and TBB versions, but we don't really have those documented in our test matrix).

2021-11-29 14:54 UTC, tommy-waltmann commented
Then we should still add CircleCI tests for python 3.10 on windows in this PR before merging. Later we can decide what to do with the rest of the CircleCI tests in another issue or PR.

2021-11-29 15:16 UTC, bdice commented
> Then we should still add CircleCI tests for python 3.10 on windows in this PR before merging. Later we can decide what to do with the rest of the CircleCI tests in another issue or PR.

Good idea. I added a Windows Python 3.10 build to CircleCI. Please take a look once CI passes.

2021-11-29 15:51 UTC, tommy-waltmann approved these changes
Looks good, I'll make an issue for the CircleCI tests which are redundant.

2021-11-29 16:02 UTC, merged