Use flake8-force instead of flake8
glotzerlab/freud pull request #902
Opened 2022-01-20 14:52 UTC by tommy-waltmann

## Description
This PR has the necessary changes to move from using the flake8 pre-commit hook to the flake8-force pre-commit hook. 

## Motivation and Context
The 4.0 release of flake8 made it unable to lint cython files (see #897 #884 ). A new workaround now exists to allow the old flake8 behavior and this PR adds the new tool to freud's pre-commit configuration and hooks.

## How Has This Been Tested?
flake8 hook should work in the CI and when pre-commit is run locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [ ] All new and existing tests passed.
- [ ] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

2022-01-20 16:50 UTC, tommy-waltmann commented
Everything appears to be in working order now.

2022-01-20 22:26 UTC, bdice requested changes

2022-01-20 22:26 UTC, bdice commented on freud/order.pyx
> +        parameter."""  # noqa W605
This probably needs to be a raw string instead. This warning is indicating that `\o` is not a valid escape sequence.

2022-01-20 22:32 UTC, bdice reviewed
Small issue that could be fixed in this PR: `freud.diffraction.DiffractionPattern.k_vectors` docs aren't rendering right:
![image](https://user-images.githubusercontent.com/3943761/150432618-43108a91-858e-484e-9382-2a1dce306370.png)

It should have a "**Type:**" block like this example, `freud.diffraction.StaticStructureFactorDirect.S_k`:
![image](https://user-images.githubusercontent.com/3943761/150432667-09751f78-d31f-4708-ac64-d47e58593623.png)

2022-01-20 22:32 UTC, bdice commented on freud/locality.pyx
> +                   :class:`matplotlib.collections.PathCollection`):
Sphinx doesn't like this. I'm not sure exactly what it needs. 
![image](https://user-images.githubusercontent.com/3943761/150432364-ac02ad66-400d-4e55-8afa-5b4042813e39.png)

2022-01-21 21:48 UTC, tommy-waltmann commented
> Small issue that could be fixed in this PR: `freud.diffraction.DiffractionPattern.k_vectors` docs aren't rendering right: ![image](https://user-images.githubusercontent.com/3943761/150432618-43108a91-858e-484e-9382-2a1dce306370.png)
> 
> It should have a "**Type:**" block like this example, `freud.diffraction.StaticStructureFactorDirect.S_k`: ![image](https://user-images.githubusercontent.com/3943761/150432667-09751f78-d31f-4708-ac64-d47e58593623.png)

The `k_vectors` not rendering right has something to do with the fact that there are two things enclosed with `` in the docstring, not just one. I have tried playing with this and have not had success.

2022-01-24 17:29 UTC, bdice approved these changes

2022-01-24 17:31 UTC, bdice commented
@tommy-waltmann The issue wasn't the backticks -- it was that the line break fell right at the end of the type specification, which messed up Sphinx's parsing. I escaped the newline to fix this.

2022-01-24 17:46 UTC, merged